// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuranBuddyAPI.Contexts;

#nullable disable

namespace QuranBuddyAPI.Migrations
{
    [DbContext(typeof(QuranDBContext))]
    [Migration("20240727154301_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("QuranBuddyAPI.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BismillahPre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RevelationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevelationPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.Verse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JuzNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transliteration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Verses");
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.Verse", b =>
                {
                    b.HasOne("QuranBuddyAPI.Models.Chapter", "Chapter")
                        .WithMany("Verses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.Chapter", b =>
                {
                    b.Navigation("Verses");
                });
#pragma warning restore 612, 618
        }
    }
}
