// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuranBuddyAPI.Contexts;

#nullable disable

namespace QuranBuddyAPI.Migrations
{
    [DbContext(typeof(QuranDBContext))]
    partial class QuranDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("QuranBuddyAPI.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BismillahPre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RevelationPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersesCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.FlashcardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("FlashcardAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAnswers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FlashcardSets");
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.Verse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HizbNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JuzNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManzilNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RubElHizbNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RukuNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SajdahNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextUthmani")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VerseKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("Verses");
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.Chapter", b =>
                {
                    b.OwnsOne("QuranBuddyAPI.Models.TranslatedName", "TranslatedName", b1 =>
                        {
                            b1.Property<int>("ChapterId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LanguageName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ChapterId");

                            b1.ToTable("Chapters");

                            b1.WithOwner()
                                .HasForeignKey("ChapterId");
                        });

                    b.Navigation("TranslatedName")
                        .IsRequired();
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.Flashcard", b =>
                {
                    b.HasOne("QuranBuddyAPI.Models.FlashcardSet", "FlashcardSet")
                        .WithMany("Flashcards")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardSet");
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.Verse", b =>
                {
                    b.HasOne("QuranBuddyAPI.Models.Chapter", "Chapter")
                        .WithMany("Verses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("QuranBuddyAPI.Models.Translation", "Translations", b1 =>
                        {
                            b1.Property<int>("VerseId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ResourceId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("VerseId", "Id");

                            b1.ToTable("Translation");

                            b1.WithOwner()
                                .HasForeignKey("VerseId");
                        });

                    b.Navigation("Chapter");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.Chapter", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("QuranBuddyAPI.Models.FlashcardSet", b =>
                {
                    b.Navigation("Flashcards");
                });
#pragma warning restore 612, 618
        }
    }
}
